### ISSUE TITLE
2 questions

### ISSUE THREAD

**Issue by caspahouzer** [mpociot/TiScreenshotDetection#3]
1. is it for 64 bit?
2. can I get the screenshot in the eventlistener?

**Comment by mpociot** [comment]
1. No it's not yet 64-bit.
2. It's not possible to get the screenshot. iOS only sends a notification without any further information.

See https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIApplication_Class/#//apple_ref/c/data/UIApplicationUserDidTakeScreenshotNotification

**Comment by caspahouzer** [comment]
Thanks
